In [1]:
import numpy as np
import pandas as pd
from scipy import stats

In [2]:
validator_exits_size = pd.read_csv('../int/validator_exits_size.csv')
validator_exits_category = pd.read_csv('../int/validator_exits_category.csv')
validator_exits_pool = pd.read_csv('../int/validator_exits_pool.csv')
active_validators_size = pd.read_csv('../int/active_validators_size.csv')
active_validators_category = pd.read_csv('../int/active_validators_category.csv')
active_validators_pool = pd.read_csv('../int/active_validators_pool.csv')

In [3]:
validator_exits_size

              slot    1  100+  2-5  20-99  6-19  total
0              0.0  0.0   0.0  0.0    0.0   0.0    0.0
1              1.0  0.0   0.0  0.0    0.0   0.0    0.0
2              2.0  0.0   0.0  0.0    0.0   0.0    0.0
3              3.0  0.0   0.0  0.0    0.0   0.0    0.0
4              4.0  0.0   0.0  0.0    0.0   0.0    0.0
...            ...  ...   ...  ...    ...   ...    ...
8986171  8986171.0  0.0   0.0  0.0    0.0   0.0    0.0
8986172  8986172.0  0.0   0.0  0.0    0.0   0.0    0.0
8986173  8986173.0  0.0   0.0  0.0    0.0   0.0    0.0
8986174  8986174.0  0.0   0.0  0.0    0.0   0.0    0.0
8986175  8986175.0  0.0   0.0  0.0    0.0   0.0    0.0

[8986176 rows x 7 columns]

In [4]:
eth_price = pd.read_csv('../int/eth_price.csv')
eth_price = eth_price[eth_price['slot'] >= 6206400]
eth_price

            slot        price  price_pct_change
6174901  6206400  1892.938911         -0.008871
6174902  6206401  1892.938911         -0.008871
6174903  6206402  1892.938911         -0.008871
6174904  6206403  1892.938911         -0.008871
6174905  6206404  1892.938911         -0.008871
...          ...          ...               ...
8954672  8986171  2976.090208         -0.014066
8954673  8986172  2976.090208         -0.014066
8954674  8986173  2976.090208         -0.014066
8954675  8986174  2976.090208         -0.014066
8954676  8986175  2976.090208         -0.014066

[2779776 rows x 3 columns]

In [5]:
validator_exits_size_set = validator_exits_size
validator_exits_size_set['slot'] = validator_exits_size_set['slot'] // 300 * 300

# Group by the day and get the last slot of each day and sum values for all columns
validator_exits_size_set = validator_exits_size_set.groupby('slot').agg(
    {
        'slot': 'last',
        '1': 'sum',
        '2-5': 'sum',
        '6-19': 'sum',
        '20-99': 'sum',
        '100+': 'sum',
        'total': 'sum'
    }
).reset_index(drop=True)

validator_exits_size_set

            slot    1  2-5  6-19  20-99  100+  total
0            0.0  0.0  0.0   0.0    0.0   0.0    0.0
1          300.0  0.0  0.0   0.0    0.0   0.0    0.0
2          600.0  0.0  0.0   0.0    0.0   0.0    0.0
3          900.0  0.0  0.0   0.0    0.0   0.0    0.0
4         1200.0  0.0  0.0   0.0    0.0   0.0    0.0
...          ...  ...  ...   ...    ...   ...    ...
29949  8984700.0  3.0  0.0   0.0    0.0  83.0   86.0
29950  8985000.0  0.0  0.0   0.0    0.0  12.0   12.0
29951  8985300.0  0.0  0.0   0.0    0.0   6.0    6.0
29952  8985600.0  1.0  0.0   0.0    0.0   0.0    1.0
29953  8985900.0  0.0  0.0   0.0    0.0   9.0    9.0

[29954 rows x 7 columns]

In [6]:
validator_exits_category_set = validator_exits_category
validator_exits_category_set['slot'] = validator_exits_category_set['slot'] // 300 * 300

# Create a dictionary for aggregation
agg_dict = {col: 'sum' for col in validator_exits_category_set.columns if col != 'slot'}
agg_dict['slot'] = 'last'

# Group by 'slot' and apply the aggregation
validator_exits_category_set = validator_exits_category_set.groupby('slot').agg(agg_dict).reset_index(drop=True)

validator_exits_category_set

,CEX,Liquid Restaking,Liquid Staking,Solo Stakers,Staking Pools,Unidentified,total,slot
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,300.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,600.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,900.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1200.0
...,...,...,...,...,...,...,...,...
29949,12.0,0.0,4.0,0.0,2.0,68.0,86.0,8984700.0
29950,0.0,0.0,3.0,0.0,9.0,0.0,12.0,8985000.0
29951,0.0,0.0,4.0,0.0,0.0,2.0,6.0,8985300.0
29952,0.0,0.0,0.0,0.0,0.0,1.0,1.0,8985600.0
29953,4.0,0.0,4.0,0.0,0.0,1.0,9.0,8985900.0

In [7]:
validator_exits_pool_set = validator_exits_pool
validator_exits_pool_set['slot'] = validator_exits_pool_set['slot'] // 300 * 300

# Create a dictionary for aggregation
agg_dict = {col: 'sum' for col in validator_exits_pool_set.columns if col != 'slot'}
agg_dict['slot'] = 'last'

# Group by 'slot' and apply the aggregation
validator_exits_pool_set = validator_exits_pool_set.groupby('slot').agg(agg_dict).reset_index(drop=True)

validator_exits_pool_set

,Binance,Bitcoin Suisse,Coinbase,Ether.Fi,Kraken,Ledger Live,Lido,Mantle,OKX,Other Stakers,Rocketpool,total,slot
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,300.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,600.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,900.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1200.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
29949,0.0,0.0,9.0,0.0,0.0,0.0,0.0,2.0,0.0,73.0,2.0,86.0,8984700.0
29950,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,9.0,3.0,12.0,8985000.0
29951,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,4.0,6.0,8985300.0
29952,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,8985600.0
29953,0.0,0.0,4.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,4.0,9.0,8985900.0

In [8]:
active_validators_size_set = active_validators_size[active_validators_size['slot'].isin(validator_exits_size_set['slot'])]
active_validators_size_set.reset_index(inplace=True)
active_validators_size_set = active_validators_size_set.drop(columns=['index'])
active_validators_size_set

            slot       1      100+     2-5    20-99     6-19      total
0            0.0  1020.0   13599.0  1049.0   3568.0   1827.0    21063.0
1          300.0  1020.0   13599.0  1049.0   3568.0   1827.0    21063.0
2          600.0  1020.0   13599.0  1049.0   3568.0   1827.0    21063.0
3          900.0  1020.0   13599.0  1049.0   3568.0   1827.0    21063.0
4         1200.0  1020.0   13599.0  1049.0   3568.0   1827.0    21063.0
...          ...     ...       ...     ...      ...      ...        ...
29949  8984700.0  9846.0  919817.0  9925.0  44358.0  18082.0  1002028.0
29950  8985000.0  9843.0  919814.0  9925.0  44358.0  18082.0  1002022.0
29951  8985300.0  9845.0  919872.0  9925.0  44358.0  18082.0  1002082.0
29952  8985600.0  9845.0  919946.0  9925.0  44358.0  18082.0  1002156.0
29953  8985900.0  9845.0  920015.0  9926.0  44358.0  18083.0  1002227.0

[29954 rows x 7 columns]

In [9]:
active_validators_category_set = active_validators_category[active_validators_category['slot'].isin(validator_exits_category_set['slot'])]
active_validators_category_set.reset_index(inplace=True)
active_validators_category_set = active_validators_category_set.drop(columns=['index'])
active_validators_category_set

,slot,CEX,Liquid Restaking,Liquid Staking,Solo Stakers,Staking Pools,Unidentified,total
0,0.0,3468.0,0.0,559.0,2309.0,622.0,14105.0,21063.0
1,300.0,3468.0,0.0,559.0,2309.0,622.0,14105.0,21063.0
2,600.0,3468.0,0.0,559.0,2309.0,622.0,14105.0,21063.0
3,900.0,3468.0,0.0,559.0,2309.0,622.0,14105.0,21063.0
4,1200.0,3468.0,0.0,559.0,2309.0,622.0,14105.0,21063.0
...,...,...,...,...,...,...,...,...
29949,8984700.0,255920.0,77793.0,331601.0,16837.0,56456.0,263421.0,1002028.0
29950,8985000.0,255908.0,77873.0,331597.0,16837.0,56454.0,263353.0,1002022.0
29951,8985300.0,255908.0,77924.0,331595.0,16837.0,56445.0,263373.0,1002082.0
29952,8985600.0,255908.0,77924.0,331591.0,16837.0,56450.0,263446.0,1002156.0
29953,8985900.0,255909.0,77939.0,331591.0,16837.0,56450.0,263501.0,1002227.0

In [10]:
active_validators_pool_set = active_validators_pool[active_validators_pool['slot'].isin(validator_exits_pool_set['slot'])]
active_validators_pool_set.reset_index(inplace=True)
active_validators_pool_set = active_validators_pool_set.drop(columns=['index'])
active_validators_pool_set

,slot,Binance,Bitcoin Suisse,Coinbase,Ether.Fi,Kraken,Ledger Live,Lido,Mantle,OKX,Other Stakers,Rocketpool,total
0,0.0,1.0,2876.0,0.0,0.0,0.0,13.0,0.0,0.0,0.0,18153.0,20.0,21063.0
1,300.0,1.0,2876.0,0.0,0.0,0.0,13.0,0.0,0.0,0.0,18153.0,20.0,21063.0
2,600.0,1.0,2876.0,0.0,0.0,0.0,13.0,0.0,0.0,0.0,18153.0,20.0,21063.0
3,900.0,1.0,2876.0,0.0,0.0,0.0,13.0,0.0,0.0,0.0,18153.0,20.0,21063.0
4,1200.0,1.0,2876.0,0.0,0.0,0.0,13.0,0.0,0.0,0.0,18153.0,20.0,21063.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
29949,8984700.0,35167.0,19013.0,138349.0,33665.0,23748.0,14723.0,290691.0,14976.0,10877.0,396087.0,24732.0,1002028.0
29950,8985000.0,35167.0,19013.0,138340.0,33745.0,23748.0,14723.0,290691.0,14974.0,10877.0,396014.0,24730.0,1002022.0
29951,8985300.0,35167.0,19013.0,138340.0,33795.0,23748.0,14723.0,290691.0,14974.0,10877.0,396026.0,24728.0,1002082.0
29952,8985600.0,35167.0,19013.0,138340.0,33795.0,23748.0,14728.0,290691.0,14974.0,10877.0,396099.0,24724.0,1002156.0
29953,8985900.0,35167.0,19013.0,138340.0,33804.0,23748.0,14728.0,290691.0,14974.0,10877.0,396161.0,24724.0,1002227.0

In [11]:
validator_exits_size_set.set_index('slot', inplace=True)
active_validators_size_set.set_index('slot', inplace=True)
validator_exit_percentage_size = validator_exits_size_set.divide(active_validators_size_set, fill_value=0) * 100
validator_exit_percentage_size.reset_index(inplace=True)
validator_exit_percentage_size

            slot         1      100+  2-5  20-99  6-19     total
0            0.0  0.000000  0.000000  0.0    0.0   0.0  0.000000
1          300.0  0.000000  0.000000  0.0    0.0   0.0  0.000000
2          600.0  0.000000  0.000000  0.0    0.0   0.0  0.000000
3          900.0  0.000000  0.000000  0.0    0.0   0.0  0.000000
4         1200.0  0.000000  0.000000  0.0    0.0   0.0  0.000000
...          ...       ...       ...  ...    ...   ...       ...
29949  8984700.0  0.030469  0.009024  0.0    0.0   0.0  0.008583
29950  8985000.0  0.000000  0.001305  0.0    0.0   0.0  0.001198
29951  8985300.0  0.000000  0.000652  0.0    0.0   0.0  0.000599
29952  8985600.0  0.010157  0.000000  0.0    0.0   0.0  0.000100
29953  8985900.0  0.000000  0.000978  0.0    0.0   0.0  0.000898

[29954 rows x 7 columns]

In [12]:
validator_exits_category_set.set_index('slot', inplace=True)
active_validators_category_set.set_index('slot', inplace=True)
validator_exit_percentage_category = validator_exits_category_set.divide(active_validators_category_set, fill_value=0) * 100
validator_exit_percentage_category.reset_index(inplace=True)
validator_exit_percentage_category

,slot,CEX,Liquid Restaking,Liquid Staking,Solo Stakers,Staking Pools,Unidentified,total
0,0.0,0.000000,NaN,0.000000,0.0,0.000000,0.000000,0.000000
1,300.0,0.000000,NaN,0.000000,0.0,0.000000,0.000000,0.000000
2,600.0,0.000000,NaN,0.000000,0.0,0.000000,0.000000,0.000000
3,900.0,0.000000,NaN,0.000000,0.0,0.000000,0.000000,0.000000
4,1200.0,0.000000,NaN,0.000000,0.0,0.000000,0.000000,0.000000
...,...,...,...,...,...,...,...,...
29949,8984700.0,0.004689,0.0,0.001206,0.0,0.003543,0.025814,0.008583
29950,8985000.0,0.000000,0.0,0.000905,0.0,0.015942,0.000000,0.001198
29951,8985300.0,0.000000,0.0,0.001206,0.0,0.000000,0.000759,0.000599
29952,8985600.0,0.000000,0.0,0.000000,0.0,0.000000,0.000380,0.000100
29953,8985900.0,0.001563,0.0,0.001206,0.0,0.000000,0.000380,0.000898

In [13]:
validator_exits_pool_set.set_index('slot', inplace=True)
active_validators_pool_set.set_index('slot', inplace=True)
validator_exit_percentage_pool = validator_exits_pool_set.divide(active_validators_pool_set, fill_value=0) * 100
validator_exit_percentage_pool.reset_index(inplace=True)
validator_exit_percentage_pool

,slot,Binance,Bitcoin Suisse,Coinbase,Ether.Fi,Kraken,Ledger Live,Lido,Mantle,OKX,Other Stakers,Rocketpool,total
0,0.0,0.0,0.0,NaN,NaN,NaN,0.0,NaN,NaN,NaN,0.000000,0.000000,0.000000
1,300.0,0.0,0.0,NaN,NaN,NaN,0.0,NaN,NaN,NaN,0.000000,0.000000,0.000000
2,600.0,0.0,0.0,NaN,NaN,NaN,0.0,NaN,NaN,NaN,0.000000,0.000000,0.000000
3,900.0,0.0,0.0,NaN,NaN,NaN,0.0,NaN,NaN,NaN,0.000000,0.000000,0.000000
4,1200.0,0.0,0.0,NaN,NaN,NaN,0.0,NaN,NaN,NaN,0.000000,0.000000,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...
29949,8984700.0,0.0,0.0,0.006505,0.0,0.0,0.0,0.0,0.013355,0.0,0.018430,0.008087,0.008583
29950,8985000.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.000000,0.0,0.002273,0.012131,0.001198
29951,8985300.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.000000,0.0,0.000505,0.016176,0.000599
29952,8985600.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.000000,0.0,0.000252,0.000000,0.000100
29953,8985900.0,0.0,0.0,0.002891,0.0,0.0,0.0,0.0,0.000000,0.0,0.000252,0.016179,0.000898

In [14]:
columns = ['1', '100+', '2-5', '20-99', '6-19', 'total']
for col in columns:
    print(validator_exit_percentage_size[col].mean())

0.001797518567377886
0.001577253182078953
0.0013819776968174678
0.0008944387687919705
0.001316424476802735
0.0015420676468236839

In [15]:
# Merge the two DataFrames on the slot column
price_elasticity_size = pd.merge(validator_exit_percentage_size, eth_price[['slot', 'price_pct_change']], on='slot')

# Drop rows with infinite values
price_elasticity_size.replace([np.inf, -np.inf], np.nan, inplace=True)

# Calculate elasticity for 'total' first
price_elasticity_size['elasticity_total'] = price_elasticity_size['total'] / price_elasticity_size['price_pct_change']
price_elasticity_size['elasticity_total'] = price_elasticity_size['elasticity_total'].replace([np.inf, -np.inf], np.nan)

# Initialize dictionaries to store elasticity values, standard deviations, t-statistics, p-values, and number of valid rows (N)
elasticity = {}
standard_deviations = {}
t_statistics = {}
p_values = {}
valid_counts = {}

# Calculate elasticity for the 'total' column
valid_total_elasticity = price_elasticity_size['elasticity_total'].dropna()
elasticity['total'] = valid_total_elasticity.mean()
standard_deviations['total'] = valid_total_elasticity.std()
t_statistics['total'] = '-'
p_values['total'] = '-'
valid_counts['total'] = len(valid_total_elasticity)

# Calculate elasticity for each column except 'total'
columns = ['1', '2-5', '6-19', '20-99', '100+']
for col in columns:
    price_elasticity_size[f'elasticity_{col}'] = price_elasticity_size[col] / price_elasticity_size['price_pct_change']
    
    # Replace infinite values with NaN
    price_elasticity_size[f'elasticity_{col}'] = price_elasticity_size[f'elasticity_{col}'].replace([np.inf, -np.inf], np.nan)
    
    # Drop NaN values for calculation purposes
    valid_elasticity = price_elasticity_size[f'elasticity_{col}'].dropna()
    
    elasticity[col] = valid_elasticity.mean()
    standard_deviations[col] = valid_elasticity.std()
    
    # Perform a two-sample t-test against the 'total' elasticity
    t_stat, p_value = stats.ttest_ind(valid_elasticity, valid_total_elasticity, equal_var=False)
    t_statistics[col] = t_stat
    p_values[col] = p_value
    
    # Store the number of valid rows
    valid_counts[col] = len(valid_elasticity)

# Print the results in the requested format
print("Elasticity Analysis Results:")
print(f'total: Mean Elasticity = {elasticity["total"]}, t(Mean) = {t_statistics["total"]}, SD = {standard_deviations["total"]}, N = {valid_counts["total"]}, p-value = {p_values["total"]}')
for col in columns:
    print(f'{col}: Mean Elasticity = {elasticity[col]}, t(Mean) = {t_statistics[col]}, SD = {standard_deviations[col]}, N = {valid_counts[col]}, p-value = {p_values[col]}')

# Display the DataFrame with elasticity columns
print(price_elasticity_size)

Elasticity Analysis Results:
total: Mean Elasticity = 0.09603047435856583, t(Mean) = -, SD = 6.25546930347153, N = 9266, p-value = -
1: Mean Elasticity = -0.016588129411378813, t(Mean) = -0.9468689400848046, SD = 9.58895286114331, N = 9266, p-value = 0.3437199186898702
2-5: Mean Elasticity = -0.0540527261874008, t(Mean) = -1.1751217754318164, SD = 10.58362105699119, N = 9266, p-value = 0.23996461041821573
6-19: Mean Elasticity = 0.07042958888910479, t(Mean) = -0.15575685144027246, SD = 14.53259271817364, N = 9266, p-value = 0.8762271812390686
20-99: Mean Elasticity = 0.15798456943899328, t(Mean) = 0.39954381996570026, SD = 13.552236229674005, N = 9266, p-value = 0.6894990852623102
100+: Mean Elasticity = 0.09590933737412541, t(Mean) = -0.001275773770578252, SD = 6.664073370566566, N = 9266, p-value = 0.9989820938696696
           slot         1      100+  2-5  20-99  6-19     total  \
0     6206400.0  0.000000  0.015735  0.0    0.0   0.0  0.014214
1     6206700.0  0.270717  0.007279  0.0    0.0   0.0  0.009773
2     6207000.0  0.015081  0.000000  0.0    0.0   0.0  0.000178
3     6207300.0  0.000000  0.000000  0.0    0.0   0.0  0.000000
4     6207600.0  0.015081  0.000000  0.0    0.0   0.0  0.000178
...         ...       ...       ...  ...    ...   ...       ...
9261  8984700.0  0.030469  0.009024  0.0    0.0   0.0  0.008583
9262  8985000.0  0.000000  0.001305  0.0    0.0   0.0  0.001198
9263  8985300.0  0.000000  0.000652  0.0    0.0   0.0  0.000599
9264  8985600.0  0.010157  0.000000  0.0    0.0   0.0  0.000100
9265  8985900.0  0.000000  0.000978  0.0    0.0   0.0  0.000898

      price_pct_change  elasticity_total  elasticity_1  elasticity_2-5  \
0            -0.008871         -1.602188     -0.000000            -0.0
1            -0.008871         -1.101630    -30.516068            -0.0
2            -0.008871         -0.020029     -1.699939            -0.0
3            -0.008871         -0.000000     -0.000000            -0.0
4            -0.008871         -0.020026     -1.699939            -0.0
...                ...               ...           ...             ...
9261         -0.014066         -0.610159     -2.166135            -0.0
9262         -0.014066         -0.085139     -0.000000            -0.0
9263         -0.014066         -0.042567     -0.000000            -0.0
9264         -0.014066         -0.007094     -0.722118            -0.0
9265         -0.014066         -0.063841     -0.000000            -0.0

      elasticity_6-19  elasticity_20-99  elasticity_100+
0                -0.0              -0.0        -1.773716
1                -0.0              -0.0        -0.820457
2                -0.0              -0.0        -0.000000
3                -0.0              -0.0        -0.000000
4                -0.0              -0.0        -0.000000
...               ...               ...              ...
9261             -0.0              -0.0        -0.641506
9262             -0.0              -0.0        -0.092748
9263             -0.0              -0.0        -0.046371
9264             -0.0              -0.0        -0.000000
9265             -0.0              -0.0        -0.069546

[9266 rows x 14 columns]

In [16]:
# Merge the two DataFrames on the slot column
price_elasticity_category = pd.merge(validator_exit_percentage_category, eth_price[['slot', 'price_pct_change']], on='slot')

# Drop rows with infinite values
price_elasticity_category.replace([np.inf, -np.inf], np.nan, inplace=True)

# Calculate elasticity for 'total' first
price_elasticity_category['elasticity_total'] = price_elasticity_category['total'] / price_elasticity_category['price_pct_change']
price_elasticity_category['elasticity_total'] = price_elasticity_category['elasticity_total'].replace([np.inf, -np.inf], np.nan)

# Initialize dictionaries to store elasticity values, standard deviations, t-statistics, p-values, and number of valid rows (N)
elasticity = {}
standard_deviations = {}
t_statistics = {}
p_values = {}
valid_counts = {}

# Calculate elasticity for the 'total' column
valid_total_elasticity = price_elasticity_category['elasticity_total'].dropna()
elasticity['total'] = valid_total_elasticity.mean()
standard_deviations['total'] = valid_total_elasticity.std()
t_statistics['total'] = '-'
p_values['total'] = '-'
valid_counts['total'] = len(valid_total_elasticity)

# Calculate elasticity for each column except 'total'
columns = validator_exit_percentage_category.columns.drop('slot')
for col in columns:
    price_elasticity_category[f'elasticity_{col}'] = price_elasticity_category[col] / price_elasticity_category['price_pct_change']
    
    # Replace infinite values with NaN
    price_elasticity_category[f'elasticity_{col}'] = price_elasticity_category[f'elasticity_{col}'].replace([np.inf, -np.inf], np.nan)
    
    # Drop NaN values for calculation purposes
    valid_elasticity = price_elasticity_category[f'elasticity_{col}'].dropna()
    
    elasticity[col] = valid_elasticity.mean()
    standard_deviations[col] = valid_elasticity.std()
    
    # Perform a two-sample t-test against the 'total' elasticity
    t_stat, p_value = stats.ttest_ind(valid_elasticity, valid_total_elasticity, equal_var=False)
    t_statistics[col] = t_stat
    p_values[col] = p_value
    
    # Store the number of valid rows
    valid_counts[col] = len(valid_elasticity)

# Print the results in the requested format
print("Elasticity Analysis Results:")
print(f'total: Mean Elasticity = {elasticity["total"]}, t(Mean) = {t_statistics["total"]}, SD = {standard_deviations["total"]}, N = {valid_counts["total"]}, p-value = {p_values["total"]}')
for col in columns:
    print(f'{col}: Mean Elasticity = {elasticity[col]}, t(Mean) = {t_statistics[col]}, SD = {standard_deviations[col]}, N = {valid_counts[col]}, p-value = {p_values[col]}')

# Display the DataFrame with elasticity columns
print(price_elasticity_category)

Elasticity Analysis Results:
total: Mean Elasticity = 0.09603047435856583, t(Mean) = 0.0, SD = 6.25546930347153, N = 9266, p-value = 1.0
CEX: Mean Elasticity = 0.135121361322051, t(Mean) = 0.25990440408552085, SD = 13.056839893921312, N = 9266, p-value = 0.7949415354709128
Liquid Restaking: Mean Elasticity = 0.5031825074666295, t(Mean) = 1.4114659460250534, SD = 27.053418133274192, N = 9266, p-value = 0.158137614537107
Liquid Staking: Mean Elasticity = 0.0035734254746533855, t(Mean) = -1.1166487155366873, SD = 4.93895782903315, N = 9266, p-value = 0.26415981184117665
Solo Stakers: Mean Elasticity = -0.40310917886979913, t(Mean) = -2.7753147781476297, SD = 16.142691723121082, N = 9266, p-value = 0.0055233761513755
Staking Pools: Mean Elasticity = 1.1772041869218453, t(Mean) = 1.8104041997061355, SD = 57.14516578810596, N = 9266, p-value = 0.07026475228527335
Unidentified: Mean Elasticity = -0.0793504709457231, t(Mean) = -1.8142252165688955, SD = 6.889157694950395, N = 9266, p-value = 0.069659374087741
total: Mean Elasticity = 0.09603047435856583, t(Mean) = 0.0, SD = 6.25546930347153, N = 9266, p-value = 1.0
           slot       CEX  Liquid Restaking  Liquid Staking  Solo Stakers  \
0     6206400.0  0.040473               0.0        0.000000           0.0
1     6206700.0  0.018726               0.0        0.000000           0.0
2     6207000.0  0.000000               0.0        0.000000           0.0
3     6207300.0  0.000000               0.0        0.000000           0.0
4     6207600.0  0.000000               0.0        0.000000           0.0
...         ...       ...               ...             ...           ...
9261  8984700.0  0.004689               0.0        0.001206           0.0
9262  8985000.0  0.000000               0.0        0.000905           0.0
9263  8985300.0  0.000000               0.0        0.001206           0.0
9264  8985600.0  0.000000               0.0        0.000000           0.0
9265  8985900.0  0.001563               0.0        0.001206           0.0

      Staking Pools  Unidentified     total  price_pct_change  \
0          0.000000      0.000000  0.014214         -0.008871
1          0.000000      0.015744  0.009773         -0.008871
2          0.000000      0.000875  0.000178         -0.008871
3          0.000000      0.000000  0.000000         -0.008871
4          0.000000      0.000875  0.000178         -0.008871
...             ...           ...       ...               ...
9261       0.003543      0.025814  0.008583         -0.014066
9262       0.015942      0.000000  0.001198         -0.014066
9263       0.000000      0.000759  0.000599         -0.014066
9264       0.000000      0.000380  0.000100         -0.014066
9265       0.000000      0.000380  0.000898         -0.014066

      elasticity_total  elasticity_CEX  elasticity_Liquid Restaking  \
0            -1.602188       -4.562274                         -0.0
1            -1.101630       -2.110799                         -0.0
2            -0.020029       -0.000000                         -0.0
3            -0.000000       -0.000000                         -0.0
4            -0.020026       -0.000000                         -0.0
...                ...             ...                          ...
9261         -0.610159       -0.333351                         -0.0
9262         -0.085139       -0.000000                         -0.0
9263         -0.042567       -0.000000                         -0.0
9264         -0.007094       -0.000000                         -0.0
9265         -0.063841       -0.111122                         -0.0

      elasticity_Liquid Staking  elasticity_Solo Stakers  \
0                     -0.000000                     -0.0
1                     -0.000000                     -0.0
2                     -0.000000                     -0.0
3                     -0.000000                     -0.0
4                     -0.000000                     -0.0
...                         ...                      ...
9261                  -0.085757                     -0.0
9262                  -0.064318                     -0.0
9263                  -0.085758                     -0.0
9264                  -0.000000                     -0.0
9265                  -0.085759                     -0.0

      elasticity_Staking Pools  elasticity_Unidentified
0                    -0.000000                -0.000000
1                    -0.000000                -1.774761
2                    -0.000000                -0.098607
3                    -0.000000                -0.000000
4                    -0.000000                -0.098602
...                        ...                      ...
9261                 -0.251851                -1.835197
9262                 -1.133371                -0.000000
9263                 -0.000000                -0.053986
9264                 -0.000000                -0.026986
9265                 -0.000000                -0.026980

[9266 rows x 16 columns]

In [17]:
# Merge the two DataFrames on the slot column
price_elasticity_pool = pd.merge(validator_exit_percentage_pool, eth_price[['slot', 'price_pct_change']], on='slot')

# Drop rows with infinite values
price_elasticity_pool.replace([np.inf, -np.inf], np.nan, inplace=True)

# Calculate elasticity for 'total' first
price_elasticity_pool['elasticity_total'] = price_elasticity_pool['total'] / price_elasticity_pool['price_pct_change']
price_elasticity_pool['elasticity_total'] = price_elasticity_pool['elasticity_total'].replace([np.inf, -np.inf], np.nan)

# Initialize dictionaries to store elasticity values, standard deviations, t-statistics, p-values, and number of valid rows (N)
elasticity = {}
standard_deviations = {}
t_statistics = {}
p_values = {}
valid_counts = {}

# Calculate elasticity for the 'total' column
valid_total_elasticity = price_elasticity_pool['elasticity_total'].dropna()
elasticity['total'] = valid_total_elasticity.mean()
standard_deviations['total'] = valid_total_elasticity.std()
t_statistics['total'] = '-'
p_values['total'] = '-'
valid_counts['total'] = len(valid_total_elasticity)

# Calculate elasticity for each column except 'total'
columns = ['Lido', 'Coinbase', 'Binance', 'Rocketpool', 'Kraken', 'OKX', 'Bitcoin Suisse', 'Ledger Live', 'Ether.Fi', 'Mantle', 'Other Stakers']
for col in columns:
    price_elasticity_pool[f'elasticity_{col}'] = price_elasticity_pool[col] / price_elasticity_pool['price_pct_change']
    
    # Replace infinite values with NaN
    price_elasticity_pool[f'elasticity_{col}'] = price_elasticity_pool[f'elasticity_{col}'].replace([np.inf, -np.inf], np.nan)
    
    # Drop NaN values for calculation purposes
    valid_elasticity = price_elasticity_pool[f'elasticity_{col}'].dropna()
    
    elasticity[col] = valid_elasticity.mean()
    standard_deviations[col] = valid_elasticity.std()
    
    # Perform a two-sample t-test against the 'total' elasticity
    t_stat, p_value = stats.ttest_ind(valid_elasticity, valid_total_elasticity, equal_var=False)
    t_statistics[col] = t_stat
    p_values[col] = p_value
    
    # Store the number of valid rows
    valid_counts[col] = len(valid_elasticity)

# Print the results in the requested format
print("Elasticity Analysis Results:")
print(f'total: Mean Elasticity = {elasticity["total"]}, t(Mean) = {t_statistics["total"]}, SD = {standard_deviations["total"]}, N = {valid_counts["total"]}, p-value = {p_values["total"]}')
for col in columns:
    print(f'{col}: Mean Elasticity = {elasticity[col]}, t(Mean) = {t_statistics[col]}, SD = {standard_deviations[col]}, N = {valid_counts[col]}, p-value = {p_values[col]}')

# Display the DataFrame with elasticity columns
print(price_elasticity_pool)

Elasticity Analysis Results:
total: Mean Elasticity = 0.09603047435856583, t(Mean) = -, SD = 6.25546930347153, N = 9266, p-value = -
Lido: Mean Elasticity = -0.05852353249506996, t(Mean) = -1.985156308907393, SD = 4.127202483670933, N = 9266, p-value = 0.04714408057230072
Coinbase: Mean Elasticity = 0.12593018006385462, t(Mean) = 0.29417838168871235, SD = 7.5226011399278025, N = 9266, p-value = 0.7686250037552422
Binance: Mean Elasticity = -0.7476067511513876, t(Mean) = -1.9224177754277203, SD = 41.77720503472669, N = 9266, p-value = 0.05458252272274002
Rocketpool: Mean Elasticity = 0.1378811155241691, t(Mean) = 0.21545938975515658, SD = 17.62000219726172, N = 9266, p-value = 0.8294129705586313
Kraken: Mean Elasticity = 0.2408969941524523, t(Mean) = 0.7144432649754722, SD = 18.48894067789358, N = 9266, p-value = 0.4749678084423443
OKX: Mean Elasticity = -0.06261279642499518, t(Mean) = -0.7224816580855133, SD = 20.190022194295427, N = 9266, p-value = 0.4700137191117294
Bitcoin Suisse: Mean Elasticity = -0.01773764001476808, t(Mean) = -1.7030533859093222, SD = 1.4897096972050858, N = 9266, p-value = 0.08858821090170062
Ledger Live: Mean Elasticity = 4.152421211042224, t(Mean) = 1.9557179816491772, SD = 199.55675453934404, N = 9266, p-value = 0.05052833799233839
Ether.Fi: Mean Elasticity = 7.0115367874772465, t(Mean) = 1.6124947587448426, SD = 310.6213760729131, N = 5247, p-value = 0.10691444339554664
Mantle: Mean Elasticity = 6.847400188954307, t(Mean) = 1.6782303473902058, SD = 281.1932038161789, N = 4887, p-value = 0.09336605713853907
Other Stakers: Mean Elasticity = 0.059392910060847924, t(Mean) = -0.32605236800510806, SD = 8.824116780843484, N = 9266, p-value = 0.7443888197312221
           slot  Binance  Bitcoin Suisse  Coinbase  Ether.Fi  Kraken  \
0     6206400.0      0.0             0.0  0.000000       NaN     0.0
1     6206700.0      0.0             0.0  0.000000       NaN     0.0
2     6207000.0      0.0             0.0  0.000000       NaN     0.0
3     6207300.0      0.0             0.0  0.000000       NaN     0.0
4     6207600.0      0.0             0.0  0.000000       NaN     0.0
...         ...      ...             ...       ...       ...     ...
9261  8984700.0      0.0             0.0  0.006505       0.0     0.0
9262  8985000.0      0.0             0.0  0.000000       0.0     0.0
9263  8985300.0      0.0             0.0  0.000000       0.0     0.0
9264  8985600.0      0.0             0.0  0.000000       0.0     0.0
9265  8985900.0      0.0             0.0  0.002891       0.0     0.0

      Ledger Live  Lido    Mantle  OKX  ...  elasticity_Coinbase  \
0             0.0   0.0       NaN  0.0  ...            -0.000000
1             0.0   0.0       NaN  0.0  ...            -0.000000
2             0.0   0.0       NaN  0.0  ...            -0.000000
3             0.0   0.0       NaN  0.0  ...            -0.000000
4             0.0   0.0       NaN  0.0  ...            -0.000000
...           ...   ...       ...  ...  ...                  ...
9261          0.0   0.0  0.013355  0.0  ...            -0.462478
9262          0.0   0.0  0.000000  0.0  ...            -0.000000
9263          0.0   0.0  0.000000  0.0  ...            -0.000000
9264          0.0   0.0  0.000000  0.0  ...            -0.000000
9265          0.0   0.0  0.000000  0.0  ...            -0.205559

      elasticity_Binance  elasticity_Rocketpool  elasticity_Kraken  \
0                   -0.0              -0.000000               -0.0
1                   -0.0              -0.000000               -0.0
2                   -0.0              -0.000000               -0.0
3                   -0.0              -0.000000               -0.0
4                   -0.0              -0.000000               -0.0
...                  ...                    ...                ...
9261                -0.0              -0.574903               -0.0
9262                -0.0              -0.862425               -0.0
9263                -0.0              -1.149993               -0.0
9264                -0.0              -0.000000               -0.0
9265                -0.0              -1.150179               -0.0

      elasticity_OKX  elasticity_Bitcoin Suisse  elasticity_Ledger Live  \
0               -0.0                       -0.0                    -0.0
1               -0.0                       -0.0                    -0.0
2               -0.0                       -0.0                    -0.0
3               -0.0                       -0.0                    -0.0
4               -0.0                       -0.0                    -0.0
...              ...                        ...                     ...
9261            -0.0                       -0.0                    -0.0
9262            -0.0                       -0.0                    -0.0
9263            -0.0                       -0.0                    -0.0
9264            -0.0                       -0.0                    -0.0
9265            -0.0                       -0.0                    -0.0

      elasticity_Ether.Fi  elasticity_Mantle  elasticity_Other Stakers
0                     NaN                NaN                 -4.713016
1                     NaN                NaN                 -3.241316
2                     NaN                NaN                 -0.058948
3                     NaN                NaN                 -0.000000
4                     NaN                NaN                 -0.058945
...                   ...                ...                       ...
9261                 -0.0           -0.94942                 -1.310257
9262                 -0.0           -0.00000                 -0.161568
9263                 -0.0           -0.00000                 -0.035903
9264                 -0.0           -0.00000                 -0.017948
9265                 -0.0           -0.00000                 -0.017945

[9266 rows x 26 columns]