In [1]:
import pandas as pd
import numpy as np

In [2]:
# Read the CSV files
rewards1 = pd.read_csv('../data/rewards_950_999.csv')
rewards2 = pd.read_csv('../data/rewards_1000_1049.csv')
rewards3 = pd.read_csv('../data/rewards_1050_1099.csv')
rewards4 = pd.read_csv('../data/rewards_1100-1139.csv')
rewards5 = pd.read_csv('../data/rewards_1140_1179.csv')
rewards6 = pd.read_csv('../data/rewards_1180_1219.csv')
rewards7 = pd.read_csv('../data/rewards_1220_1259.csv')

# Concatenate the dataframes
rewards = pd.concat([rewards1, rewards2, rewards3, rewards4, rewards5, rewards6, rewards7], ignore_index=True)
rewards = rewards[rewards['earnings'] <= 1000000000]
rewards.reset_index()

rewards

           validator_index   day  earnings
0                     2463   950   2642655
1                   551546   950   2639773
2                    54903   950   2639679
3                   506494   950   2645579
4                   311332   950   2645579
...                    ...   ...       ...
271841332            94570  1244   2139156
271841333          1345184  1244   2136826
271841334          1155058  1244   2129797
271841335           212928  1244   2131744
271841336           135660  1244   2120334

[271841322 rows x 3 columns]

In [3]:
del rewards1
del rewards2
del rewards3
del rewards4
del rewards5
del rewards6
del rewards7

In [4]:
#1061 238725 225
rewards.loc[rewards['day'] == 1061, 'epoch'] = 238594

In [5]:
# Calculate the epoch value for each day based on the known day 1061
base_day = 1061
base_epoch = 238594
epochs_per_day = 225

# Create a function to calculate the epoch for a given day
def calculate_epoch(day):
    day_difference = day - base_day
    return base_epoch + day_difference * epochs_per_day

# Apply the function to calculate the epoch for each day
rewards['epoch'] = rewards['day'].apply(calculate_epoch)

# Display the dataframe to verify the changes
rewards

           validator_index   day  earnings   epoch
0                     2463   950   2642655  213619
1                   551546   950   2639773  213619
2                    54903   950   2639679  213619
3                   506494   950   2645579  213619
4                   311332   950   2645579  213619
...                    ...   ...       ...     ...
271841332            94570  1244   2139156  279769
271841333          1345184  1244   2136826  279769
271841334          1155058  1244   2129797  279769
271841335           212928  1244   2131744  279769
271841336           135660  1244   2120334  279769

[271841322 rows x 4 columns]

In [6]:
rewards.drop(columns=('day'))

           validator_index  earnings   epoch
0                     2463   2642655  213619
1                   551546   2639773  213619
2                    54903   2639679  213619
3                   506494   2645579  213619
4                   311332   2645579  213619
...                    ...       ...     ...
271841332            94570   2139156  279769
271841333          1345184   2136826  279769
271841334          1155058   2129797  279769
271841335           212928   2131744  279769
271841336           135660   2120334  279769

[271841322 rows x 3 columns]

In [7]:
rewards['median'] = rewards.groupby('epoch')['earnings'].transform('median')
rewards

           validator_index   day  earnings   epoch     median
0                     2463   950   2642655  213619  2619919.0
1                   551546   950   2639773  213619  2619919.0
2                    54903   950   2639679  213619  2619919.0
3                   506494   950   2645579  213619  2619919.0
4                   311332   950   2645579  213619  2619919.0
...                    ...   ...       ...     ...        ...
271841332            94570  1244   2139156  279769  2125400.0
271841333          1345184  1244   2136826  279769  2125400.0
271841334          1155058  1244   2129797  279769  2125400.0
271841335           212928  1244   2131744  279769  2125400.0
271841336           135660  1244   2120334  279769  2125400.0

[271841322 rows x 5 columns]

In [8]:
# Select the rows where 'earnings' are greater than 10000000
priority_n_block_rewards = rewards[rewards['earnings'] > 10000000].copy()
priority_n_block_rewards['priority_n_block_rewards'] = priority_n_block_rewards['earnings'] - priority_n_block_rewards['median']
priority_n_block_rewards = priority_n_block_rewards['priority_n_block_rewards']

In [9]:
rewards['priority_n_block_rewards'] = priority_n_block_rewards
rewards = rewards.fillna(0)
rewards

,validator_index,day,earnings,epoch,median,priority_n_block_rewards
0,2463,950,2642655,213619,2619919.0,0.0
1,551546,950,2639773,213619,2619919.0,0.0
2,54903,950,2639679,213619,2619919.0,0.0
3,506494,950,2645579,213619,2619919.0,0.0
4,311332,950,2645579,213619,2619919.0,0.0
...,...,...,...,...,...,...
271841332,94570,1244,2139156,279769,2125400.0,0.0
271841333,1345184,1244,2136826,279769,2125400.0,0.0
271841334,1155058,1244,2129797,279769,2125400.0,0.0
271841335,212928,1244,2131744,279769,2125400.0,0.0
271841336,135660,1244,2120334,279769,2125400.0,0.0

In [10]:
validator_metadata = pd.read_csv('../int/validator_metadata_v2.csv')
largest_pools = ('Lido','Coinbase','Binance','Rocketpool','Kraken','OKX','Bitcoin Suisse','Ledger Live','Ether.Fi','Mantle')
validator_metadata.loc[~validator_metadata['pool'].isin(largest_pools), 'pool'] = 'Other Stakers'
validator_metadata

/var/folders/mb/5hm6pgrs3zj_1m_kgvpt40jw0000gn/T/ipykernel_98776/2832579726.py:1: DtypeWarning: Columns (9) have mixed types. Specify dtype option on import or set low_memory=False.
  validator_metadata = pd.read_csv('int/validator_metadata_v2.csv')

,validator_index,pool,category,pool_size,pool_size_label,activation_epoch,exit_epoch,withdrawal_address,deposit_address,second_deposit_address
0,18846,Other Stakers,CEX,1371.0,100+,0.0,252781.0,0xc771172ae08b5fc37b3ac3d445225928de883876,0x0038598ecb3b308ebc6c6e2c635bacaa3c5298a3,NaN
1,18891,Other Stakers,CEX,1371.0,100+,0.0,252783.0,0xc771172ae08b5fc37b3ac3d445225928de883876,0x0038598ecb3b308ebc6c6e2c635bacaa3c5298a3,NaN
2,16368,Other Stakers,Liquid Staking,786.0,100+,0.0,194722.0,0x1cd9f4e1449840aec32686e3b20d0f7b104562ed,0x197939c1ca20c2b506d6811d8b6cdb3394471074,NaN
3,537,Other Stakers,Solo Stakers,218.0,100+,0.0,NaN,NaN,0x1db3439a222c519ab44bb1144fc28167b4fa6ee6,NaN
4,559,Other Stakers,Solo Stakers,218.0,100+,0.0,NaN,NaN,0x1db3439a222c519ab44bb1144fc28167b4fa6ee6,NaN
...,...,...,...,...,...,...,...,...,...,...
1391510,366084,Other Stakers,NaN,25625.0,100+,116722.0,242454.0,0xeee27662c2b8eba3cd936a23f039f3189633e4c8,0xeee27662c2b8eba3cd936a23f039f3189633e4c8,NaN
1391511,366148,Other Stakers,NaN,25625.0,100+,116734.0,248692.0,0xeee27662c2b8eba3cd936a23f039f3189633e4c8,0xeee27662c2b8eba3cd936a23f039f3189633e4c8,NaN
1391512,366146,Other Stakers,NaN,25625.0,100+,116734.0,248723.0,0xeee27662c2b8eba3cd936a23f039f3189633e4c8,0xeee27662c2b8eba3cd936a23f039f3189633e4c8,NaN
1391513,366159,Other Stakers,NaN,25625.0,100+,116737.0,248754.0,0xeee27662c2b8eba3cd936a23f039f3189633e4c8,0xeee27662c2b8eba3cd936a23f039f3189633e4c8,NaN
1391514,367688,Other Stakers,NaN,25625.0,100+,117043.0,248709.0,0xeee27662c2b8eba3cd936a23f039f3189633e4c8,0xeee27662c2b8eba3cd936a23f039f3189633e4c8,NaN

In [11]:
rewards = pd.merge(rewards, validator_metadata[['validator_index', 'pool', 'category', 'pool_size_label']], on='validator_index', how='left')
rewards.drop(columns=['day', 'median'])

,validator_index,earnings,epoch,priority_n_block_rewards,pool,category,pool_size_label
0,2463,2642655,213619,0.0,Other Stakers,NaN,100+
1,551546,2639773,213619,0.0,Other Stakers,Unidentified,100+
2,54903,2639679,213619,0.0,Binance,CEX,100+
3,506494,2645579,213619,0.0,Lido,Liquid Staking,100+
4,311332,2645579,213619,0.0,Lido,Liquid Staking,100+
...,...,...,...,...,...,...,...
271841317,94570,2139156,279769,0.0,Other Stakers,Liquid Staking,100+
271841318,1345184,2136826,279769,0.0,Ledger Live,Staking Pools,100+
271841319,1155058,2129797,279769,0.0,Other Stakers,Unidentified,100+
271841320,212928,2131744,279769,0.0,Lido,Liquid Staking,100+
271841321,135660,2120334,279769,0.0,Lido,Liquid Staking,100+

In [12]:
rewards

,validator_index,day,earnings,epoch,median,priority_n_block_rewards,pool,category,pool_size_label
0,2463,950,2642655,213619,2619919.0,0.0,Other Stakers,NaN,100+
1,551546,950,2639773,213619,2619919.0,0.0,Other Stakers,Unidentified,100+
2,54903,950,2639679,213619,2619919.0,0.0,Binance,CEX,100+
3,506494,950,2645579,213619,2619919.0,0.0,Lido,Liquid Staking,100+
4,311332,950,2645579,213619,2619919.0,0.0,Lido,Liquid Staking,100+
...,...,...,...,...,...,...,...,...,...
271841317,94570,1244,2139156,279769,2125400.0,0.0,Other Stakers,Liquid Staking,100+
271841318,1345184,1244,2136826,279769,2125400.0,0.0,Ledger Live,Staking Pools,100+
271841319,1155058,1244,2129797,279769,2125400.0,0.0,Other Stakers,Unidentified,100+
271841320,212928,1244,2131744,279769,2125400.0,0.0,Lido,Liquid Staking,100+
271841321,135660,1244,2120334,279769,2125400.0,0.0,Lido,Liquid Staking,100+

In [ ]:
rewards.to_parquet('../int/rewards_epoch.parquet', engine='auto')